package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"conduit-monorepo/conduit-api/app/api"
	"conduit-monorepo/conduit-api/app/auth"
)

func main() {
	authService := &auth.Service{}
	authHandler := api.NewAuthHandler(authService, false, 0)
	groupsHandler := api.NewGroupsHandler(nil)
	collectionsHandler := api.NewCollectionsHandler(nil)
	formsHandler := api.NewFormsHandler(nil)
	router := api.NewRouter(authHandler, groupsHandler, collectionsHandler, formsHandler, authService)

	routes := router.Routes()
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].Path == routes[j].Path {
			return routes[i].Method < routes[j].Method
		}
		return routes[i].Path < routes[j].Path
	})

	var b strings.Builder
	b.WriteString("# API Routes\n\n")
	b.WriteString("Autogenerated from Gin router wiring.\n\n")
	b.WriteString("Generated: " + time.Now().UTC().Format(time.RFC3339) + "\n\n")
	b.WriteString("## Auth Notes\n\n")
	b.WriteString("- Access token: send in Authorization header as Bearer token.\n")
	b.WriteString("- Refresh token: send in X-Refresh-Token header or refresh_token cookie.\n")
	b.WriteString("- Protected endpoint: GET /api/auth/me requires a valid access token.\n\n")
	b.WriteString("## Route Table\n\n")
	b.WriteString("| Method | Path | Handler |\n")
	b.WriteString("|---|---|---|\n")
	for _, route := range routes {
		b.WriteString(fmt.Sprintf("| %s | %s | %s |\n", route.Method, route.Path, route.Handler))
	}
	b.WriteString("\n")

	outPath := filepath.Join("docs", "api-routes.md")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}
