// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_id, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenID   string             `json:"token_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserCredential = `-- name: CreateUserCredential :one
INSERT INTO users (email, password_hash, display_name, pfp_url)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, display_name, pfp_url, created_at
`

type CreateUserCredentialParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  string      `json:"display_name"`
	PfpUrl       pgtype.Text `json:"pfp_url"`
}

func (q *Queries) CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserCredential,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.PfpUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.PfpUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByTokenID = `-- name: GetRefreshTokenByTokenID :one
SELECT id, user_id, token_id, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_id = $1
`

func (q *Queries) GetRefreshTokenByTokenID(ctx context.Context, tokenID string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByTokenID, tokenID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCredentialByEmail = `-- name: GetUserCredentialByEmail :one
SELECT id, email, password_hash, display_name, pfp_url, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserCredentialByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserCredentialByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.PfpUrl,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenID string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenID)
	return err
}

const revokeRefreshTokensForUser = `-- name: RevokeRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokensForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensForUser, userID)
	return err
}
