// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE token_hash = $1
	AND used_at IS NULL
	AND expires_at > NOW()
RETURNING user_id
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash string) (int64, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_id, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenID   string             `json:"token_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserCredential = `-- name: CreateUserCredential :one
INSERT INTO users (email, password_hash, display_name, pfp_url)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, display_name, pfp_url, created_at
`

type CreateUserCredentialParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  string      `json:"display_name"`
	PfpUrl       pgtype.Text `json:"pfp_url"`
}

func (q *Queries) CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserCredential,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.PfpUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.PfpUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByTokenID = `-- name: GetRefreshTokenByTokenID :one
SELECT id, user_id, token_id, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_id = $1
`

func (q *Queries) GetRefreshTokenByTokenID(ctx context.Context, tokenID string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByTokenID, tokenID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCredentialByEmail = `-- name: GetUserCredentialByEmail :one
SELECT id, email, password_hash, display_name, pfp_url, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserCredentialByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserCredentialByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.PfpUrl,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetTokensUsedForUser = `-- name: MarkPasswordResetTokensUsedForUser :exec
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) MarkPasswordResetTokensUsedForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokensUsedForUser, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenID string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenID)
	return err
}

const revokeRefreshTokensForUser = `-- name: RevokeRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokensForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensForUser, userID)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
