// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeCollection = `-- name: CloseCollection :one
UPDATE collections
SET status = 'closed'
WHERE id = $1
RETURNING id, group_id, amount, deadline, status, created_at
`

func (q *Queries) CloseCollection(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRow(ctx, closeCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Amount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (group_id, amount, deadline)
VALUES ($1, $2, $3)
RETURNING id, group_id, amount, deadline, status, created_at
`

type CreateCollectionParams struct {
	GroupID  int64              `json:"group_id"`
	Amount   int64              `json:"amount"`
	Deadline pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection, arg.GroupID, arg.Amount, arg.Deadline)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Amount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listCollectionsByGroup = `-- name: ListCollectionsByGroup :many
SELECT id, group_id, amount, deadline, status, created_at
FROM collections
WHERE group_id = $1
ORDER BY id DESC
`

func (q *Queries) ListCollectionsByGroup(ctx context.Context, groupID int64) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollectionsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Amount,
			&i.Deadline,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
