// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeCollection = `-- name: CloseCollection :one
UPDATE collections
SET status = 'closed'
WHERE id = $1 AND group_id = $2
RETURNING id, group_id, amount, deadline, status, created_at
`

type CloseCollectionParams struct {
	ID      int64 `json:"id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) CloseCollection(ctx context.Context, arg CloseCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, closeCollection, arg.ID, arg.GroupID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Amount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (group_id, amount, deadline)
VALUES ($1, $2, $3)
RETURNING id, group_id, amount, deadline, status, created_at
`

type CreateCollectionParams struct {
	GroupID  int64              `json:"group_id"`
	Amount   int64              `json:"amount"`
	Deadline pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection, arg.GroupID, arg.Amount, arg.Deadline)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Amount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :one
DELETE FROM collections
WHERE id = $1 AND group_id = $2
RETURNING id, group_id, amount, deadline, status, created_at
`

type DeleteCollectionParams struct {
	ID      int64 `json:"id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, deleteCollection, arg.ID, arg.GroupID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Amount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, group_id, amount, deadline, status, created_at
FROM collections
WHERE id = $1
`

func (q *Queries) GetCollection(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Amount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listCollectionsByGroup = `-- name: ListCollectionsByGroup :many
SELECT id, group_id, amount, deadline, status, created_at
FROM collections
WHERE group_id = $1
ORDER BY id DESC
`

func (q *Queries) ListCollectionsByGroup(ctx context.Context, groupID int64) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollectionsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Amount,
			&i.Deadline,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET amount = $2, deadline = $3
WHERE id = $1 AND group_id = $4
RETURNING id, group_id, amount, deadline, status, created_at
`

type UpdateCollectionParams struct {
	ID       int64              `json:"id"`
	Amount   int64              `json:"amount"`
	Deadline pgtype.Timestamptz `json:"deadline"`
	GroupID  int64              `json:"group_id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.Amount,
		arg.Deadline,
		arg.GroupID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Amount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
