// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFormAnswer = `-- name: AddFormAnswer :one
INSERT INTO collection_form_answers (submission_id, field_id, value_text, value_json)
VALUES ($1, $2, $3, $4)
RETURNING id, submission_id, field_id, value_text, value_json, created_at
`

type AddFormAnswerParams struct {
	SubmissionID int64       `json:"submission_id"`
	FieldID      int64       `json:"field_id"`
	ValueText    pgtype.Text `json:"value_text"`
	ValueJson    []byte      `json:"value_json"`
}

func (q *Queries) AddFormAnswer(ctx context.Context, arg AddFormAnswerParams) (CollectionFormAnswer, error) {
	row := q.db.QueryRow(ctx, addFormAnswer,
		arg.SubmissionID,
		arg.FieldID,
		arg.ValueText,
		arg.ValueJson,
	)
	var i CollectionFormAnswer
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.FieldID,
		&i.ValueText,
		&i.ValueJson,
		&i.CreatedAt,
	)
	return i, err
}

const createCollectionForm = `-- name: CreateCollectionForm :one
INSERT INTO collection_forms (collection_id, title, description, is_required)
VALUES ($1, $2, $3, $4)
RETURNING id, collection_id, title, description, is_required, created_at, updated_at
`

type CreateCollectionFormParams struct {
	CollectionID int64       `json:"collection_id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	IsRequired   bool        `json:"is_required"`
}

func (q *Queries) CreateCollectionForm(ctx context.Context, arg CreateCollectionFormParams) (CollectionForm, error) {
	row := q.db.QueryRow(ctx, createCollectionForm,
		arg.CollectionID,
		arg.Title,
		arg.Description,
		arg.IsRequired,
	)
	var i CollectionForm
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Title,
		&i.Description,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCollectionFormField = `-- name: CreateCollectionFormField :one
INSERT INTO collection_form_fields (
    form_id,
    field_key,
    label,
    field_type,
    placeholder,
    is_required,
    options,
    sort_order
)
VALUES ($1, $2, $3, $4::form_field_type, $5, $6, $7, $8)
RETURNING id, form_id, field_key, label, field_type, placeholder, is_required, options, sort_order, created_at
`

type CreateCollectionFormFieldParams struct {
	FormID      int64         `json:"form_id"`
	FieldKey    string        `json:"field_key"`
	Label       string        `json:"label"`
	Column4     FormFieldType `json:"column_4"`
	Placeholder pgtype.Text   `json:"placeholder"`
	IsRequired  bool          `json:"is_required"`
	Options     []byte        `json:"options"`
	SortOrder   int32         `json:"sort_order"`
}

func (q *Queries) CreateCollectionFormField(ctx context.Context, arg CreateCollectionFormFieldParams) (CollectionFormField, error) {
	row := q.db.QueryRow(ctx, createCollectionFormField,
		arg.FormID,
		arg.FieldKey,
		arg.Label,
		arg.Column4,
		arg.Placeholder,
		arg.IsRequired,
		arg.Options,
		arg.SortOrder,
	)
	var i CollectionFormField
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.FieldKey,
		&i.Label,
		&i.FieldType,
		&i.Placeholder,
		&i.IsRequired,
		&i.Options,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createFormSubmission = `-- name: CreateFormSubmission :one
INSERT INTO collection_form_submissions (form_id, collection_id, user_id)
VALUES ($1, $2, $3)
RETURNING id, form_id, collection_id, user_id, submitted_at
`

type CreateFormSubmissionParams struct {
	FormID       int64 `json:"form_id"`
	CollectionID int64 `json:"collection_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) (CollectionFormSubmission, error) {
	row := q.db.QueryRow(ctx, createFormSubmission, arg.FormID, arg.CollectionID, arg.UserID)
	var i CollectionFormSubmission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.CollectionID,
		&i.UserID,
		&i.SubmittedAt,
	)
	return i, err
}

const deleteCollectionForm = `-- name: DeleteCollectionForm :one
DELETE FROM collection_forms
WHERE id = $1
RETURNING id, collection_id, title, description, is_required, created_at, updated_at
`

func (q *Queries) DeleteCollectionForm(ctx context.Context, id int64) (CollectionForm, error) {
	row := q.db.QueryRow(ctx, deleteCollectionForm, id)
	var i CollectionForm
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Title,
		&i.Description,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFormAnswer = `-- name: DeleteFormAnswer :one
DELETE FROM collection_form_answers
WHERE id = $1
RETURNING id, submission_id, field_id, value_text, value_json, created_at
`

func (q *Queries) DeleteFormAnswer(ctx context.Context, id int64) (CollectionFormAnswer, error) {
	row := q.db.QueryRow(ctx, deleteFormAnswer, id)
	var i CollectionFormAnswer
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.FieldID,
		&i.ValueText,
		&i.ValueJson,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFormSubmission = `-- name: DeleteFormSubmission :one
DELETE FROM collection_form_submissions
WHERE id = $1
RETURNING id, form_id, collection_id, user_id, submitted_at
`

func (q *Queries) DeleteFormSubmission(ctx context.Context, id int64) (CollectionFormSubmission, error) {
	row := q.db.QueryRow(ctx, deleteFormSubmission, id)
	var i CollectionFormSubmission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.CollectionID,
		&i.UserID,
		&i.SubmittedAt,
	)
	return i, err
}

const getCollectionFormByCollectionID = `-- name: GetCollectionFormByCollectionID :one
SELECT id, collection_id, title, description, is_required, created_at, updated_at
FROM collection_forms
WHERE collection_id = $1
`

func (q *Queries) GetCollectionFormByCollectionID(ctx context.Context, collectionID int64) (CollectionForm, error) {
	row := q.db.QueryRow(ctx, getCollectionFormByCollectionID, collectionID)
	var i CollectionForm
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Title,
		&i.Description,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionFormByID = `-- name: GetCollectionFormByID :one
SELECT id, collection_id, title, description, is_required, created_at, updated_at
FROM collection_forms
WHERE id = $1
`

func (q *Queries) GetCollectionFormByID(ctx context.Context, id int64) (CollectionForm, error) {
	row := q.db.QueryRow(ctx, getCollectionFormByID, id)
	var i CollectionForm
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Title,
		&i.Description,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormAnswerByID = `-- name: GetFormAnswerByID :one
SELECT id, submission_id, field_id, value_text, value_json, created_at
FROM collection_form_answers
WHERE id = $1
`

func (q *Queries) GetFormAnswerByID(ctx context.Context, id int64) (CollectionFormAnswer, error) {
	row := q.db.QueryRow(ctx, getFormAnswerByID, id)
	var i CollectionFormAnswer
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.FieldID,
		&i.ValueText,
		&i.ValueJson,
		&i.CreatedAt,
	)
	return i, err
}

const getFormSubmissionByID = `-- name: GetFormSubmissionByID :one
SELECT id, form_id, collection_id, user_id, submitted_at
FROM collection_form_submissions
WHERE id = $1
`

func (q *Queries) GetFormSubmissionByID(ctx context.Context, id int64) (CollectionFormSubmission, error) {
	row := q.db.QueryRow(ctx, getFormSubmissionByID, id)
	var i CollectionFormSubmission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.CollectionID,
		&i.UserID,
		&i.SubmittedAt,
	)
	return i, err
}

const listCollectionFormFields = `-- name: ListCollectionFormFields :many
SELECT id, form_id, field_key, label, field_type, placeholder, is_required, options, sort_order, created_at
FROM collection_form_fields
WHERE form_id = $1
ORDER BY sort_order
`

func (q *Queries) ListCollectionFormFields(ctx context.Context, formID int64) ([]CollectionFormField, error) {
	rows, err := q.db.Query(ctx, listCollectionFormFields, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionFormField
	for rows.Next() {
		var i CollectionFormField
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.FieldKey,
			&i.Label,
			&i.FieldType,
			&i.Placeholder,
			&i.IsRequired,
			&i.Options,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormAnswersBySubmission = `-- name: ListFormAnswersBySubmission :many
SELECT id, submission_id, field_id, value_text, value_json, created_at
FROM collection_form_answers
WHERE submission_id = $1
ORDER BY id
`

func (q *Queries) ListFormAnswersBySubmission(ctx context.Context, submissionID int64) ([]CollectionFormAnswer, error) {
	rows, err := q.db.Query(ctx, listFormAnswersBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionFormAnswer
	for rows.Next() {
		var i CollectionFormAnswer
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.FieldID,
			&i.ValueText,
			&i.ValueJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormSubmissionsByCollection = `-- name: ListFormSubmissionsByCollection :many
SELECT id, form_id, collection_id, user_id, submitted_at
FROM collection_form_submissions
WHERE collection_id = $1
ORDER BY submitted_at DESC
`

func (q *Queries) ListFormSubmissionsByCollection(ctx context.Context, collectionID int64) ([]CollectionFormSubmission, error) {
	rows, err := q.db.Query(ctx, listFormSubmissionsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionFormSubmission
	for rows.Next() {
		var i CollectionFormSubmission
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.CollectionID,
			&i.UserID,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollectionForm = `-- name: UpdateCollectionForm :one
UPDATE collection_forms
SET title = $2, description = $3, is_required = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, collection_id, title, description, is_required, created_at, updated_at
`

type UpdateCollectionFormParams struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsRequired  bool        `json:"is_required"`
}

func (q *Queries) UpdateCollectionForm(ctx context.Context, arg UpdateCollectionFormParams) (CollectionForm, error) {
	row := q.db.QueryRow(ctx, updateCollectionForm,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsRequired,
	)
	var i CollectionForm
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Title,
		&i.Description,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFormAnswer = `-- name: UpdateFormAnswer :one
UPDATE collection_form_answers
SET value_text = $2, value_json = $3
WHERE id = $1
RETURNING id, submission_id, field_id, value_text, value_json, created_at
`

type UpdateFormAnswerParams struct {
	ID        int64       `json:"id"`
	ValueText pgtype.Text `json:"value_text"`
	ValueJson []byte      `json:"value_json"`
}

func (q *Queries) UpdateFormAnswer(ctx context.Context, arg UpdateFormAnswerParams) (CollectionFormAnswer, error) {
	row := q.db.QueryRow(ctx, updateFormAnswer, arg.ID, arg.ValueText, arg.ValueJson)
	var i CollectionFormAnswer
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.FieldID,
		&i.ValueText,
		&i.ValueJson,
		&i.CreatedAt,
	)
	return i, err
}

const updateFormSubmission = `-- name: UpdateFormSubmission :one
UPDATE collection_form_submissions
SET form_id = $2, collection_id = $3
WHERE id = $1
RETURNING id, form_id, collection_id, user_id, submitted_at
`

type UpdateFormSubmissionParams struct {
	ID           int64 `json:"id"`
	FormID       int64 `json:"form_id"`
	CollectionID int64 `json:"collection_id"`
}

func (q *Queries) UpdateFormSubmission(ctx context.Context, arg UpdateFormSubmissionParams) (CollectionFormSubmission, error) {
	row := q.db.QueryRow(ctx, updateFormSubmission, arg.ID, arg.FormID, arg.CollectionID)
	var i CollectionFormSubmission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.CollectionID,
		&i.UserID,
		&i.SubmittedAt,
	)
	return i, err
}
