// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
)

const addMembership = `-- name: AddMembership :one
INSERT INTO memberships (user_id, group_id, role)
VALUES ($1, $2, $3::membership_role)
RETURNING user_id, group_id, role, created_at
`

type AddMembershipParams struct {
	UserID  int64          `json:"user_id"`
	GroupID int64          `json:"group_id"`
	Column3 MembershipRole `json:"column_3"`
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, addMembership, arg.UserID, arg.GroupID, arg.Column3)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (owner_id, name)
VALUES ($1, $2)
RETURNING id, owner_id, name, created_at
`

type CreateGroupParams struct {
	OwnerID int64  `json:"owner_id"`
	Name    string `json:"name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.OwnerID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupMemberships = `-- name: ListGroupMemberships :many
SELECT user_id, group_id, role, created_at
FROM memberships
WHERE group_id = $1
ORDER BY user_id
`

func (q *Queries) ListGroupMemberships(ctx context.Context, groupID int64) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listGroupMemberships, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByOwner = `-- name: ListGroupsByOwner :many
SELECT id, owner_id, name, created_at
FROM groups
WHERE owner_id = $1
ORDER BY id DESC
`

func (q *Queries) ListGroupsByOwner(ctx context.Context, ownerID int64) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
