// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMembership = `-- name: AddMembership :one
WITH params(user_id, group_id, role) AS (
	VALUES ($1::bigint, $2::bigint, $3::membership_role)
)
INSERT INTO memberships (user_id, group_id, role)
SELECT user_id, group_id, role FROM params
ON CONFLICT (user_id, group_id) DO UPDATE SET role = EXCLUDED.role
RETURNING user_id, group_id, role, created_at
`

type AddMembershipParams struct {
	Column1 int64          `json:"column_1"`
	Column2 int64          `json:"column_2"`
	Column3 MembershipRole `json:"column_3"`
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, addMembership, arg.Column1, arg.Column2, arg.Column3)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (owner_id, name, is_open, join_code)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, is_open, join_code, created_at
`

type CreateGroupParams struct {
	OwnerID  int64  `json:"owner_id"`
	Name     string `json:"name"`
	IsOpen   bool   `json:"is_open"`
	JoinCode string `json:"join_code"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.OwnerID,
		arg.Name,
		arg.IsOpen,
		arg.JoinCode,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IsOpen,
		&i.JoinCode,
		&i.CreatedAt,
	)
	return i, err
}

const createJoinRequest = `-- name: CreateJoinRequest :one
WITH params(user_id, group_id, status) AS (
	VALUES ($1::bigint, $2::bigint, $3::join_request_status)
)
INSERT INTO join_requests (user_id, group_id, status)
SELECT user_id, group_id, status FROM params
RETURNING user_id, group_id, status, created_at
`

type CreateJoinRequestParams struct {
	Column1 int64             `json:"column_1"`
	Column2 int64             `json:"column_2"`
	Column3 JoinRequestStatus `json:"column_3"`
}

func (q *Queries) CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (JoinRequest, error) {
	row := q.db.QueryRow(ctx, createJoinRequest, arg.Column1, arg.Column2, arg.Column3)
	var i JoinRequest
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :one
DELETE FROM groups
WHERE id = $1
RETURNING id, owner_id, name, is_open, join_code, created_at
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRow(ctx, deleteGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IsOpen,
		&i.JoinCode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :one
DELETE FROM memberships
WHERE user_id = $1 AND group_id = $2
RETURNING user_id, group_id, role, created_at
`

type DeleteMembershipParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, deleteMembership, arg.UserID, arg.GroupID)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, owner_id, name, is_open, join_code, created_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IsOpen,
		&i.JoinCode,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByJoinCode = `-- name: GetGroupByJoinCode :one
SELECT id, owner_id, name, is_open, join_code, created_at
FROM groups
WHERE join_code = $1
`

func (q *Queries) GetGroupByJoinCode(ctx context.Context, joinCode string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByJoinCode, joinCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IsOpen,
		&i.JoinCode,
		&i.CreatedAt,
	)
	return i, err
}

const getJoinRequest = `-- name: GetJoinRequest :one
SELECT user_id, group_id, status, created_at
FROM join_requests
WHERE user_id = $1 AND group_id = $2
`

type GetJoinRequestParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) GetJoinRequest(ctx context.Context, arg GetJoinRequestParams) (JoinRequest, error) {
	row := q.db.QueryRow(ctx, getJoinRequest, arg.UserID, arg.GroupID)
	var i JoinRequest
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupMemberships = `-- name: ListGroupMemberships :many
SELECT user_id, group_id, role, created_at
FROM memberships
WHERE group_id = $1
ORDER BY user_id
`

func (q *Queries) ListGroupMemberships(ctx context.Context, groupID int64) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listGroupMemberships, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByMember = `-- name: ListGroupsByMember :many
SELECT g.id, g.owner_id, g.name, g.is_open, g.join_code, g.created_at
FROM groups g
JOIN memberships m ON m.group_id = g.id
WHERE m.user_id = $1
ORDER BY g.id DESC
`

func (q *Queries) ListGroupsByMember(ctx context.Context, userID int64) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.IsOpen,
			&i.JoinCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByOwner = `-- name: ListGroupsByOwner :many
SELECT id, owner_id, name, is_open, join_code, created_at
FROM groups
WHERE owner_id = $1
ORDER BY id DESC
`

func (q *Queries) ListGroupsByOwner(ctx context.Context, ownerID int64) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.IsOpen,
			&i.JoinCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJoinRequestsByGroup = `-- name: ListJoinRequestsByGroup :many
SELECT user_id, group_id, status, created_at
FROM join_requests
WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListJoinRequestsByGroup(ctx context.Context, groupID int64) ([]JoinRequest, error) {
	rows, err := q.db.Query(ctx, listJoinRequestsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JoinRequest
	for rows.Next() {
		var i JoinRequest
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJoinRequestsByUser = `-- name: ListJoinRequestsByUser :many
SELECT jr.user_id, jr.group_id, jr.status, jr.created_at, g.name as group_name
FROM join_requests jr
JOIN groups g ON g.id = jr.group_id
WHERE jr.user_id = $1 AND jr.status = 'pending'
ORDER BY jr.created_at DESC
`

type ListJoinRequestsByUserRow struct {
	UserID    int64              `json:"user_id"`
	GroupID   int64              `json:"group_id"`
	Status    JoinRequestStatus  `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	GroupName string             `json:"group_name"`
}

func (q *Queries) ListJoinRequestsByUser(ctx context.Context, userID int64) ([]ListJoinRequestsByUserRow, error) {
	rows, err := q.db.Query(ctx, listJoinRequestsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJoinRequestsByUserRow
	for rows.Next() {
		var i ListJoinRequestsByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.Status,
			&i.CreatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = $2
WHERE id = $1
RETURNING id, owner_id, name, is_open, join_code, created_at
`

type UpdateGroupParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IsOpen,
		&i.JoinCode,
		&i.CreatedAt,
	)
	return i, err
}

const updateGroupIsOpen = `-- name: UpdateGroupIsOpen :one
UPDATE groups
SET is_open = $2
WHERE id = $1
RETURNING id, owner_id, name, is_open, join_code, created_at
`

type UpdateGroupIsOpenParams struct {
	ID     int64 `json:"id"`
	IsOpen bool  `json:"is_open"`
}

func (q *Queries) UpdateGroupIsOpen(ctx context.Context, arg UpdateGroupIsOpenParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupIsOpen, arg.ID, arg.IsOpen)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IsOpen,
		&i.JoinCode,
		&i.CreatedAt,
	)
	return i, err
}

const updateJoinRequestStatus = `-- name: UpdateJoinRequestStatus :one
WITH params(user_id, group_id, status) AS (
	VALUES ($1::bigint, $2::bigint, $3::join_request_status)
)
UPDATE join_requests
SET status = params.status
FROM params
WHERE join_requests.user_id = params.user_id AND join_requests.group_id = params.group_id
RETURNING join_requests.user_id, join_requests.group_id, join_requests.status, join_requests.created_at
`

type UpdateJoinRequestStatusParams struct {
	Column1 int64             `json:"column_1"`
	Column2 int64             `json:"column_2"`
	Column3 JoinRequestStatus `json:"column_3"`
}

func (q *Queries) UpdateJoinRequestStatus(ctx context.Context, arg UpdateJoinRequestStatusParams) (JoinRequest, error) {
	row := q.db.QueryRow(ctx, updateJoinRequestStatus, arg.Column1, arg.Column2, arg.Column3)
	var i JoinRequest
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateMembership = `-- name: UpdateMembership :one
WITH params(user_id, group_id, role) AS (
	VALUES ($1::bigint, $2::bigint, $3::membership_role)
)
UPDATE memberships
SET role = params.role
FROM params
WHERE user_id = params.user_id AND group_id = params.group_id
RETURNING user_id, group_id, role, created_at
`

type UpdateMembershipParams struct {
	Column1 int64          `json:"column_1"`
	Column2 int64          `json:"column_2"`
	Column3 MembershipRole `json:"column_3"`
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembership, arg.Column1, arg.Column2, arg.Column3)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
