// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CashPaymentStatus string

const (
	CashPaymentStatusPending   CashPaymentStatus = "pending"
	CashPaymentStatusConfirmed CashPaymentStatus = "confirmed"
)

func (e *CashPaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CashPaymentStatus(s)
	case string:
		*e = CashPaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CashPaymentStatus: %T", src)
	}
	return nil
}

type NullCashPaymentStatus struct {
	CashPaymentStatus CashPaymentStatus `json:"cash_payment_status"`
	Valid             bool              `json:"valid"` // Valid is true if CashPaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCashPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CashPaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CashPaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCashPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CashPaymentStatus), nil
}

type CollectionStatus string

const (
	CollectionStatusActive CollectionStatus = "active"
	CollectionStatusClosed CollectionStatus = "closed"
)

func (e *CollectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CollectionStatus(s)
	case string:
		*e = CollectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CollectionStatus: %T", src)
	}
	return nil
}

type NullCollectionStatus struct {
	CollectionStatus CollectionStatus `json:"collection_status"`
	Valid            bool             `json:"valid"` // Valid is true if CollectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCollectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CollectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CollectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCollectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CollectionStatus), nil
}

type FormFieldType string

const (
	FormFieldTypeText     FormFieldType = "text"
	FormFieldTypeTextarea FormFieldType = "textarea"
	FormFieldTypeNumber   FormFieldType = "number"
	FormFieldTypeDate     FormFieldType = "date"
	FormFieldTypeSelect   FormFieldType = "select"
	FormFieldTypeCheckbox FormFieldType = "checkbox"
	FormFieldTypeEmail    FormFieldType = "email"
	FormFieldTypePhone    FormFieldType = "phone"
)

func (e *FormFieldType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FormFieldType(s)
	case string:
		*e = FormFieldType(s)
	default:
		return fmt.Errorf("unsupported scan type for FormFieldType: %T", src)
	}
	return nil
}

type NullFormFieldType struct {
	FormFieldType FormFieldType `json:"form_field_type"`
	Valid         bool          `json:"valid"` // Valid is true if FormFieldType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFormFieldType) Scan(value interface{}) error {
	if value == nil {
		ns.FormFieldType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FormFieldType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFormFieldType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FormFieldType), nil
}

type JoinRequestStatus string

const (
	JoinRequestStatusPending  JoinRequestStatus = "pending"
	JoinRequestStatusApproved JoinRequestStatus = "approved"
	JoinRequestStatusDenied   JoinRequestStatus = "denied"
)

func (e *JoinRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JoinRequestStatus(s)
	case string:
		*e = JoinRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JoinRequestStatus: %T", src)
	}
	return nil
}

type NullJoinRequestStatus struct {
	JoinRequestStatus JoinRequestStatus `json:"join_request_status"`
	Valid             bool              `json:"valid"` // Valid is true if JoinRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJoinRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JoinRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JoinRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJoinRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JoinRequestStatus), nil
}

type MembershipRole string

const (
	MembershipRoleAdmin     MembershipRole = "admin"
	MembershipRoleMember    MembershipRole = "member"
	MembershipRoleCollector MembershipRole = "collector"
	MembershipRoleModerator MembershipRole = "moderator"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type OutboxStatus string

const (
	OutboxStatusPending   OutboxStatus = "pending"
	OutboxStatusProcessed OutboxStatus = "processed"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus `json:"outbox_status"`
	Valid        bool         `json:"valid"` // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodStripe PaymentMethod = "stripe"
	PaymentMethodCash   PaymentMethod = "cash"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusPending PaymentStatus = "pending"
	PaymentStatusPaid    PaymentStatus = "paid"
	PaymentStatusFailed  PaymentStatus = "failed"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type SubscriptionTier string

const (
	SubscriptionTierFree       SubscriptionTier = "free"
	SubscriptionTierStarter    SubscriptionTier = "starter"
	SubscriptionTierGrowth     SubscriptionTier = "growth"
	SubscriptionTierEnterprise SubscriptionTier = "enterprise"
)

func (e *SubscriptionTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionTier(s)
	case string:
		*e = SubscriptionTier(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionTier: %T", src)
	}
	return nil
}

type NullSubscriptionTier struct {
	SubscriptionTier SubscriptionTier `json:"subscription_tier"`
	Valid            bool             `json:"valid"` // Valid is true if SubscriptionTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionTier) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionTier), nil
}

type CashPayment struct {
	ID          int64              `json:"id"`
	PaymentID   int64              `json:"payment_id"`
	Status      CashPaymentStatus  `json:"status"`
	ConfirmedBy pgtype.Int8        `json:"confirmed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
}

type Collection struct {
	ID        int64              `json:"id"`
	GroupID   int64              `json:"group_id"`
	Amount    int64              `json:"amount"`
	Deadline  pgtype.Timestamptz `json:"deadline"`
	Status    CollectionStatus   `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CollectionForm struct {
	ID           int64              `json:"id"`
	CollectionID int64              `json:"collection_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	IsRequired   bool               `json:"is_required"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CollectionFormAnswer struct {
	ID           int64              `json:"id"`
	SubmissionID int64              `json:"submission_id"`
	FieldID      int64              `json:"field_id"`
	ValueText    pgtype.Text        `json:"value_text"`
	ValueJson    []byte             `json:"value_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CollectionFormField struct {
	ID          int64              `json:"id"`
	FormID      int64              `json:"form_id"`
	FieldKey    string             `json:"field_key"`
	Label       string             `json:"label"`
	FieldType   FormFieldType      `json:"field_type"`
	Placeholder pgtype.Text        `json:"placeholder"`
	IsRequired  bool               `json:"is_required"`
	Options     []byte             `json:"options"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CollectionFormSubmission struct {
	ID           int64              `json:"id"`
	FormID       int64              `json:"form_id"`
	CollectionID int64              `json:"collection_id"`
	UserID       int64              `json:"user_id"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
}

type Group struct {
	ID        int64              `json:"id"`
	OwnerID   int64              `json:"owner_id"`
	Name      string             `json:"name"`
	IsOpen    bool               `json:"is_open"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type JoinRequest struct {
	UserID    int64              `json:"user_id"`
	GroupID   int64              `json:"group_id"`
	Status    JoinRequestStatus  `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	UserID    int64              `json:"user_id"`
	GroupID   int64              `json:"group_id"`
	Role      MembershipRole     `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OrganizationSubscription struct {
	ID                           int64              `json:"id"`
	GroupID                      int64              `json:"group_id"`
	Tier                         SubscriptionTier   `json:"tier"`
	MemberLimit                  int32              `json:"member_limit"`
	TransactionCapacityPerPeriod int32              `json:"transaction_capacity_per_period"`
	TransactionFeeBps            int32              `json:"transaction_fee_bps"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID          int64              `json:"id"`
	EventType   string             `json:"event_type"`
	AggregateID int64              `json:"aggregate_id"`
	Payload     []byte             `json:"payload"`
	Status      OutboxStatus       `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type PasswordResetToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                    int64              `json:"id"`
	UserID                int64              `json:"user_id"`
	CollectionID          int64              `json:"collection_id"`
	Amount                int64              `json:"amount"`
	Status                PaymentStatus      `json:"status"`
	Method                PaymentMethod      `json:"method"`
	StripePaymentIntentID pgtype.Text        `json:"stripe_payment_intent_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenID   string             `json:"token_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SubscriptionUsagePeriod struct {
	ID               int64              `json:"id"`
	GroupID          int64              `json:"group_id"`
	PeriodStart      pgtype.Timestamptz `json:"period_start"`
	PeriodEnd        pgtype.Timestamptz `json:"period_end"`
	TransactionCount int32              `json:"transaction_count"`
	GrossAmount      int64              `json:"gross_amount"`
	FeeAmount        int64              `json:"fee_amount"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	PfpUrl       pgtype.Text        `json:"pfp_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
