// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmCashPayment = `-- name: ConfirmCashPayment :one
UPDATE cash_payments
SET status = 'confirmed',
	confirmed_by = $1::bigint,
	confirmed_at = NOW()
WHERE payment_id = $2
	AND status = 'pending'
RETURNING id, payment_id, status, confirmed_by, created_at, confirmed_at
`

type ConfirmCashPaymentParams struct {
	ConfirmedBy int64 `json:"confirmed_by"`
	PaymentID   int64 `json:"payment_id"`
}

func (q *Queries) ConfirmCashPayment(ctx context.Context, arg ConfirmCashPaymentParams) (CashPayment, error) {
	row := q.db.QueryRow(ctx, confirmCashPayment, arg.ConfirmedBy, arg.PaymentID)
	var i CashPayment
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Status,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const createCashPayment = `-- name: CreateCashPayment :one
INSERT INTO cash_payments (payment_id)
VALUES ($1)
RETURNING id, payment_id, status, confirmed_by, created_at, confirmed_at
`

func (q *Queries) CreateCashPayment(ctx context.Context, paymentID int64) (CashPayment, error) {
	row := q.db.QueryRow(ctx, createCashPayment, paymentID)
	var i CashPayment
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Status,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, collection_id, base_amount, fee_amount, total_amount, method, stripe_payment_intent_id)
VALUES ($1, $2, $3, $4, $5, $6::payment_method, $7)
RETURNING id, user_id, collection_id, base_amount, fee_amount, total_amount, status, method, stripe_payment_intent_id, created_at
`

type CreatePaymentParams struct {
	UserID                int64         `json:"user_id"`
	CollectionID          int64         `json:"collection_id"`
	BaseAmount            int64         `json:"base_amount"`
	FeeAmount             int64         `json:"fee_amount"`
	TotalAmount           int64         `json:"total_amount"`
	Column6               PaymentMethod `json:"column_6"`
	StripePaymentIntentID pgtype.Text   `json:"stripe_payment_intent_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.CollectionID,
		arg.BaseAmount,
		arg.FeeAmount,
		arg.TotalAmount,
		arg.Column6,
		arg.StripePaymentIntentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.BaseAmount,
		&i.FeeAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Method,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}

const getCashPaymentByPaymentID = `-- name: GetCashPaymentByPaymentID :one
SELECT id, payment_id, status, confirmed_by, created_at, confirmed_at
FROM cash_payments
WHERE payment_id = $1
LIMIT 1
`

func (q *Queries) GetCashPaymentByPaymentID(ctx context.Context, paymentID int64) (CashPayment, error) {
	row := q.db.QueryRow(ctx, getCashPaymentByPaymentID, paymentID)
	var i CashPayment
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Status,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, user_id, collection_id, base_amount, fee_amount, total_amount, status, method, stripe_payment_intent_id, created_at
FROM payments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.BaseAmount,
		&i.FeeAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Method,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByStripePaymentIntentID = `-- name: GetPaymentByStripePaymentIntentID :one
SELECT id, user_id, collection_id, base_amount, fee_amount, total_amount, status, method, stripe_payment_intent_id, created_at
FROM payments
WHERE stripe_payment_intent_id = $1::text
LIMIT 1
`

func (q *Queries) GetPaymentByStripePaymentIntentID(ctx context.Context, stripePaymentIntentID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByStripePaymentIntentID, stripePaymentIntentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.BaseAmount,
		&i.FeeAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Method,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByCollection = `-- name: ListPaymentsByCollection :many
SELECT DISTINCT ON (user_id) id, user_id, collection_id, base_amount, fee_amount, total_amount, status, method, stripe_payment_intent_id, created_at
FROM payments
WHERE collection_id = $1
ORDER BY user_id, 
         CASE WHEN status = 'paid' THEN 1 ELSE 2 END, 
         created_at DESC
`

func (q *Queries) ListPaymentsByCollection(ctx context.Context, collectionID int64) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.BaseAmount,
			&i.FeeAmount,
			&i.TotalAmount,
			&i.Status,
			&i.Method,
			&i.StripePaymentIntentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET status = 'failed'
WHERE id = $1
	AND status = 'pending'
RETURNING id, user_id, collection_id, base_amount, fee_amount, total_amount, status, method, stripe_payment_intent_id, created_at
`

func (q *Queries) MarkPaymentFailed(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.BaseAmount,
		&i.FeeAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Method,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :one
UPDATE payments
SET status = 'paid'
WHERE id = $1
	AND status = 'pending'
RETURNING id, user_id, collection_id, base_amount, fee_amount, total_amount, status, method, stripe_payment_intent_id, created_at
`

func (q *Queries) MarkPaymentPaid(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentPaid, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.BaseAmount,
		&i.FeeAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Method,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}
