// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, collection_id, amount, method, stripe_payment_intent_id)
VALUES ($1, $2, $3, $4::payment_method, $5)
RETURNING id, user_id, collection_id, amount, status, method, stripe_payment_intent_id, created_at
`

type CreatePaymentParams struct {
	UserID                int64         `json:"user_id"`
	CollectionID          int64         `json:"collection_id"`
	Amount                int64         `json:"amount"`
	Column4               PaymentMethod `json:"column_4"`
	StripePaymentIntentID pgtype.Text   `json:"stripe_payment_intent_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.CollectionID,
		arg.Amount,
		arg.Column4,
		arg.StripePaymentIntentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.Amount,
		&i.Status,
		&i.Method,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByStripePaymentIntentID = `-- name: GetPaymentByStripePaymentIntentID :one
SELECT id, user_id, collection_id, amount, status, method, stripe_payment_intent_id, created_at
FROM payments
WHERE stripe_payment_intent_id = $1::text
LIMIT 1
`

func (q *Queries) GetPaymentByStripePaymentIntentID(ctx context.Context, stripePaymentIntentID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByStripePaymentIntentID, stripePaymentIntentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.Amount,
		&i.Status,
		&i.Method,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByCollection = `-- name: ListPaymentsByCollection :many
SELECT id, user_id, collection_id, amount, status, method, stripe_payment_intent_id, created_at
FROM payments
WHERE collection_id = $1
ORDER BY id DESC
`

func (q *Queries) ListPaymentsByCollection(ctx context.Context, collectionID int64) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Amount,
			&i.Status,
			&i.Method,
			&i.StripePaymentIntentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET status = 'failed'
WHERE id = $1
	AND status = 'pending'
RETURNING id, user_id, collection_id, amount, status, method, stripe_payment_intent_id, created_at
`

func (q *Queries) MarkPaymentFailed(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.Amount,
		&i.Status,
		&i.Method,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :one
UPDATE payments
SET status = 'paid'
WHERE id = $1
	AND status = 'pending'
RETURNING id, user_id, collection_id, amount, status, method, stripe_payment_intent_id, created_at
`

func (q *Queries) MarkPaymentPaid(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentPaid, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.Amount,
		&i.Status,
		&i.Method,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}
