// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddMembership(ctx context.Context, arg AddMembershipParams) (Membership, error)
	CloseCollection(ctx context.Context, id int64) (Collection, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateUser(ctx context.Context, email string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListCollectionsByGroup(ctx context.Context, groupID int64) ([]Collection, error)
	ListGroupMemberships(ctx context.Context, groupID int64) ([]Membership, error)
	ListGroupsByOwner(ctx context.Context, ownerID int64) ([]Group, error)
	ListPaymentsByCollection(ctx context.Context, collectionID int64) ([]Payment, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkPaymentFailed(ctx context.Context, id int64) (Payment, error)
	MarkPaymentPaid(ctx context.Context, id int64) (Payment, error)
}

var _ Querier = (*Queries)(nil)
