// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddFormAnswer(ctx context.Context, arg AddFormAnswerParams) (CollectionFormAnswer, error)
	AddMembership(ctx context.Context, arg AddMembershipParams) (Membership, error)
	CloseCollection(ctx context.Context, arg CloseCollectionParams) (Collection, error)
	ConsumePasswordResetToken(ctx context.Context, tokenHash string) (int64, error)
	CountMembersByGroup(ctx context.Context, groupID int64) (int64, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateCollectionForm(ctx context.Context, arg CreateCollectionFormParams) (CollectionForm, error)
	CreateCollectionFormField(ctx context.Context, arg CreateCollectionFormFieldParams) (CollectionFormField, error)
	CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) (CollectionFormSubmission, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (JoinRequest, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUsagePeriod(ctx context.Context, arg CreateUsagePeriodParams) (SubscriptionUsagePeriod, error)
	CreateUser(ctx context.Context, email string) (User, error)
	CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) (User, error)
	DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (Collection, error)
	DeleteCollectionForm(ctx context.Context, id int64) (CollectionForm, error)
	DeleteFormAnswer(ctx context.Context, id int64) (CollectionFormAnswer, error)
	DeleteFormSubmission(ctx context.Context, id int64) (CollectionFormSubmission, error)
	DeleteGroup(ctx context.Context, id int64) (Group, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (Membership, error)
	GetCollection(ctx context.Context, id int64) (Collection, error)
	GetCollectionFormByCollectionID(ctx context.Context, collectionID int64) (CollectionForm, error)
	GetCollectionFormByID(ctx context.Context, id int64) (CollectionForm, error)
	GetFormAnswerByID(ctx context.Context, id int64) (CollectionFormAnswer, error)
	GetFormSubmissionByID(ctx context.Context, id int64) (CollectionFormSubmission, error)
	GetGroupByID(ctx context.Context, id int64) (Group, error)
	GetOrganizationSubscriptionByGroup(ctx context.Context, groupID int64) (OrganizationSubscription, error)
	GetPaymentByStripePaymentIntentID(ctx context.Context, stripePaymentIntentID string) (Payment, error)
	GetRefreshTokenByTokenID(ctx context.Context, tokenID string) (RefreshToken, error)
	GetUsagePeriodByGroupAndStart(ctx context.Context, arg GetUsagePeriodByGroupAndStartParams) (SubscriptionUsagePeriod, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserCredentialByEmail(ctx context.Context, email string) (User, error)
	IncrementUsageForPayment(ctx context.Context, arg IncrementUsageForPaymentParams) (SubscriptionUsagePeriod, error)
	ListCollectionFormFields(ctx context.Context, formID int64) ([]CollectionFormField, error)
	ListCollectionsByGroup(ctx context.Context, groupID int64) ([]Collection, error)
	ListFormAnswersBySubmission(ctx context.Context, submissionID int64) ([]CollectionFormAnswer, error)
	ListFormSubmissionsByCollection(ctx context.Context, collectionID int64) ([]CollectionFormSubmission, error)
	ListGroupMemberships(ctx context.Context, groupID int64) ([]Membership, error)
	ListGroupsByOwner(ctx context.Context, ownerID int64) ([]Group, error)
	ListJoinRequestsByGroup(ctx context.Context, groupID int64) ([]JoinRequest, error)
	ListPaymentsByCollection(ctx context.Context, collectionID int64) ([]Payment, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkPasswordResetTokensUsedForUser(ctx context.Context, userID int64) error
	MarkPaymentFailed(ctx context.Context, id int64) (Payment, error)
	MarkPaymentPaid(ctx context.Context, id int64) (Payment, error)
	RevokeRefreshToken(ctx context.Context, tokenID string) error
	RevokeRefreshTokensForUser(ctx context.Context, userID int64) error
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateCollectionForm(ctx context.Context, arg UpdateCollectionFormParams) (CollectionForm, error)
	UpdateFormAnswer(ctx context.Context, arg UpdateFormAnswerParams) (CollectionFormAnswer, error)
	UpdateFormSubmission(ctx context.Context, arg UpdateFormSubmissionParams) (CollectionFormSubmission, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateGroupIsOpen(ctx context.Context, arg UpdateGroupIsOpenParams) (Group, error)
	UpdateJoinRequestStatus(ctx context.Context, arg UpdateJoinRequestStatusParams) (JoinRequest, error)
	UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (Membership, error)
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpsertOrganizationSubscription(ctx context.Context, arg UpsertOrganizationSubscriptionParams) (OrganizationSubscription, error)
}

var _ Querier = (*Queries)(nil)
