// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMembersByGroup = `-- name: CountMembersByGroup :one
SELECT COUNT(*)::BIGINT
FROM memberships
WHERE group_id = $1
`

func (q *Queries) CountMembersByGroup(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersByGroup, groupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUsagePeriod = `-- name: CreateUsagePeriod :one
INSERT INTO subscription_usage_periods (
    group_id,
    period_start,
    period_end,
    transaction_count,
    gross_amount,
    fee_amount
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, period_start, period_end, transaction_count, gross_amount, fee_amount, created_at, updated_at
`

type CreateUsagePeriodParams struct {
	GroupID          int64              `json:"group_id"`
	PeriodStart      pgtype.Timestamptz `json:"period_start"`
	PeriodEnd        pgtype.Timestamptz `json:"period_end"`
	TransactionCount int32              `json:"transaction_count"`
	GrossAmount      int64              `json:"gross_amount"`
	FeeAmount        int64              `json:"fee_amount"`
}

func (q *Queries) CreateUsagePeriod(ctx context.Context, arg CreateUsagePeriodParams) (SubscriptionUsagePeriod, error) {
	row := q.db.QueryRow(ctx, createUsagePeriod,
		arg.GroupID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TransactionCount,
		arg.GrossAmount,
		arg.FeeAmount,
	)
	var i SubscriptionUsagePeriod
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TransactionCount,
		&i.GrossAmount,
		&i.FeeAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationSubscriptionByGroup = `-- name: GetOrganizationSubscriptionByGroup :one
SELECT id, group_id, tier, member_limit, transaction_capacity_per_period, transaction_fee_bps, created_at, updated_at
FROM organization_subscriptions
WHERE group_id = $1
LIMIT 1 FOR UPDATE
`

func (q *Queries) GetOrganizationSubscriptionByGroup(ctx context.Context, groupID int64) (OrganizationSubscription, error) {
	row := q.db.QueryRow(ctx, getOrganizationSubscriptionByGroup, groupID)
	var i OrganizationSubscription
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Tier,
		&i.MemberLimit,
		&i.TransactionCapacityPerPeriod,
		&i.TransactionFeeBps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsagePeriodByGroupAndStart = `-- name: GetUsagePeriodByGroupAndStart :one
SELECT id, group_id, period_start, period_end, transaction_count, gross_amount, fee_amount, created_at, updated_at
FROM subscription_usage_periods
WHERE group_id = $1
  AND period_start = $2
LIMIT 1 FOR UPDATE
`

type GetUsagePeriodByGroupAndStartParams struct {
	GroupID     int64              `json:"group_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
}

func (q *Queries) GetUsagePeriodByGroupAndStart(ctx context.Context, arg GetUsagePeriodByGroupAndStartParams) (SubscriptionUsagePeriod, error) {
	row := q.db.QueryRow(ctx, getUsagePeriodByGroupAndStart, arg.GroupID, arg.PeriodStart)
	var i SubscriptionUsagePeriod
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TransactionCount,
		&i.GrossAmount,
		&i.FeeAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementUsageForPayment = `-- name: IncrementUsageForPayment :one
UPDATE subscription_usage_periods
SET transaction_count = transaction_count + $3,
    gross_amount = gross_amount + $4,
    fee_amount = fee_amount + $5,
    updated_at = NOW()
WHERE group_id = $1
  AND period_start = $2
RETURNING id, group_id, period_start, period_end, transaction_count, gross_amount, fee_amount, created_at, updated_at
`

type IncrementUsageForPaymentParams struct {
	GroupID          int64              `json:"group_id"`
	PeriodStart      pgtype.Timestamptz `json:"period_start"`
	TransactionCount int32              `json:"transaction_count"`
	GrossAmount      int64              `json:"gross_amount"`
	FeeAmount        int64              `json:"fee_amount"`
}

func (q *Queries) IncrementUsageForPayment(ctx context.Context, arg IncrementUsageForPaymentParams) (SubscriptionUsagePeriod, error) {
	row := q.db.QueryRow(ctx, incrementUsageForPayment,
		arg.GroupID,
		arg.PeriodStart,
		arg.TransactionCount,
		arg.GrossAmount,
		arg.FeeAmount,
	)
	var i SubscriptionUsagePeriod
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TransactionCount,
		&i.GrossAmount,
		&i.FeeAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationSubscription = `-- name: UpsertOrganizationSubscription :one
INSERT INTO organization_subscriptions (
    group_id,
    tier,
    member_limit,
    transaction_capacity_per_period,
    transaction_fee_bps
)
VALUES (
  $1,
  $2::subscription_tier,
  $3,
  $4,
  $5
)
ON CONFLICT (group_id)
DO UPDATE SET
    tier = EXCLUDED.tier,
    member_limit = EXCLUDED.member_limit,
    transaction_capacity_per_period = EXCLUDED.transaction_capacity_per_period,
    transaction_fee_bps = EXCLUDED.transaction_fee_bps,
    updated_at = NOW()
RETURNING id, group_id, tier, member_limit, transaction_capacity_per_period, transaction_fee_bps, created_at, updated_at
`

type UpsertOrganizationSubscriptionParams struct {
	GroupID                      int64            `json:"group_id"`
	Tier                         SubscriptionTier `json:"tier"`
	MemberLimit                  int32            `json:"member_limit"`
	TransactionCapacityPerPeriod int32            `json:"transaction_capacity_per_period"`
	TransactionFeeBps            int32            `json:"transaction_fee_bps"`
}

func (q *Queries) UpsertOrganizationSubscription(ctx context.Context, arg UpsertOrganizationSubscriptionParams) (OrganizationSubscription, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationSubscription,
		arg.GroupID,
		arg.Tier,
		arg.MemberLimit,
		arg.TransactionCapacityPerPeriod,
		arg.TransactionFeeBps,
	)
	var i OrganizationSubscription
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Tier,
		&i.MemberLimit,
		&i.TransactionCapacityPerPeriod,
		&i.TransactionFeeBps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
